package tanks.gui.screen;

import com.codedisaster.steamworks.SteamResult;

public class SteamResults
{
    public static final String[] messages = new String[]
    {
        "Success.",
        "Generic failure.",
        "Your Steam client doesn't have a connection to the back-end.",
        "Password/ticket is invalid.",
        "You are logged in elsewhere.",
        "Protocol version is incorrect.",
        "A parameter is incorrect.",
        "File was not found.",
        "Called method is busy - action not taken.",
        "Called object was in an invalid state.",
        "The name was invalid.",
        "The email was invalid.",
        "The name is not unique.",
        "Access is denied.",
        "Operation timed out.",
        "You are VAC2 banned.",
        "Account not found.",
        "The Steam ID was invalid.",
        "The requested service is currently unavailable.",
        "You are not logged on.",
        "Request is pending, it may be in process or waiting on third party.",
        "Encryption or Decryption failed.",
        "Insufficient privilege.",
        "Too much of a good thing.",
        "Guest pass access has been revoked.",
        "License/Guest pass the user is trying to access is expired.",
        "Guest pass has already been redeemed by account, cannot be used again.",
        "The request is a duplicate and the action has already occurred in the past, ignored this time.",
        "All the games in this guest pass redemption request are already owned by the user.",
        "IP address not found.",
        "Failed to write change to the data store.",
        "Failed to acquire access lock for this operation.",
        "The logon session has been replaced.",
        "Failed to connect.",
        "The authentication handshake has failed.",
        "There has been a generic IO failure.",
        "The remote server has disconnected.",
        "Failed to find the shopping cart requested.",
        "A user blocked the action.",
        "The target is ignoring sender.",
        "Nothing matching the request found.",
        "The account is disabled.",
        "This service is not accepting content changes right now.",
        "Account doesn't have value, so this feature isn't available.",
        "Allowed to take this action, but only because requester is admin.",
        "A Version mismatch in content transmitted within the Steam protocol.",
        "The current CM can't service the user making a request, user should try another.",
        "You are already logged in elsewhere, this cached credential login has failed.",
        "You are logged in elsewhere.",
        "Long running operation has suspended/paused. (eg. content download.).",
        "Operation has been canceled, typically by user. (eg. a content download.).",
        "Operation canceled because data is ill formed or unrecoverable.",
        "Operation canceled - not enough disk space.",
        "The remote or IPC call has failed.",
        "Password could not be verified as it's unset server side.",
        "External account (PSN, Facebook...) is not linked to a Steam account.",
        "PSN ticket was invalid.",
        "External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first.",
        "The sync cannot resume due to a conflict between the local and remote files.",
        "The requested new password is not allowed.",
        "New value is the same as the old one.",
        "Account login denied due to 2nd factor authentication failure.",
        "The requested new password is not legal.",
        "Account login denied due to auth code invalid.",
        "Account login denied due to 2nd factor auth failure - and no mail has been sent.",
        "The users hardware does not support Intel's Identity Protection Technology (IPT).",
        "Intel's Identity Protection Technology (IPT) has failed to initialize.",
        "Operation failed due to parental control restrictions.",
        "Facebook query returned an error.",
        "Account login denied due to an expired auth code.",
        "The login failed due to an IP restriction.",
        "Your account is currently locked for use. This is likely due to a hijacking and pending ownership verification.",
        "The logon failed because your account's email is not verified.",
        "There is no URL matching the provided values.",
        "Bad Response due to a Parse failure, missing field, etc.",
        "You must log in again.",
        "The value entered is outside the acceptable range.",
        "Something happened that Steam didn't expect to ever happen. Get your act together, Steam!.",
        "The requested service has been configured to be unavailable.",
        "The files submitted to the CEG server are not valid.",
        "The device being used is not allowed to perform this action.",
        "The action could not be complete because it is region restricted.",
        "Temporary rate limit exceeded, try again later.",
        "Need two-factor code to login.",
        "The thing you're trying to access has been deleted.",
        "Login attempt failed, try to throttle response to possible attacker.",
        "Two factor authentication (Steam Guard) code is incorrect.",
        "The activation code for two-factor authentication (Steam Guard) didn't match.",
        "The current account has been associated with multiple partners.",
        "The data has not been modified.",
        "The account does not have a mobile device associated with it.",
        "The time presented is out of range or tolerance.",
        "SMS code failure - no match, none pending, etc.",
        "Too many accounts access this resource.",
        "Too many changes to this account.",
        "Too many changes to this phone.",
        "Cannot refund to payment method, must use wallet.",
        "Cannot send an email.",
        "Can't perform operation until payment has settled.",
        "You need to provide a valid captcha.",
        "A game server login token owned by this token's owner has been banned.",
        "Game server owner is denied for some other reason such as account locked, community ban, vac ban, missing phone, etc.",
        "The type of thing we were requested to act on is invalid.",
        "The IP address has been banned from taking this action.",
        "This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use.",
        "You don't have enough wallet funds to complete the action.",
        "There are too many of this thing pending already.",
        "Unknown error"
    };

    public static String getMessage(SteamResult r)
    {
        return messages[r.ordinal()];
    }
}
