name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
    - name: JDK17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
    - name: init-steamworks4j
        run: mvn install:install-file    -Dfile=libs/steamworks4j-1.10 0-SNAPSHOT.jar    -DgroupId=com.code-disaster.steamworks4j    -DartifactId=steamworks4j    -Dversion=1.10.0-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true
    - name: init-steamworks4j-lwjgl
        run: mvn install:install-file    -Dfile=libs/steamworks4j-lwjgl3-1.10.0-SNAPSHOT.jar    -DgroupId=com.code-disaster.steamworks4j    -DartifactId=steamworks4j-lwjgl3    -Dversion=1.10.0-SNAPSHOT    -Dpackaging=jar    -DgeneratePom=true
    - name: Build
        run: mvn package
    - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: Tanks.jar
  codacy:
    name: Codacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Analyze
        uses: codacy/codacy-analysis-cli-action@master
