name: Check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: JDK8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.312
          distribution: liberica

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Determine artifact name
        id: find_artifact
        run: |
          file=$(basename build/libs/*.jar)
          echo "artifact_name=$file" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_artifact.outputs.artifact_name }}
          path: build/libs/*.jar

#  codacy:
#    name: Codacy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@main
#      - name: Analyze
#        uses: codacy/codacy-analysis-cli-action@master
