name: Scan
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scan
        uses: JetBrains/qodana-action@v2022.3.4
      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
